language: go
sudo: false
go:
  - master
  - 1.x
  - 1.8
  - 1.7
  - 1.6
  - tip
matrix:
  allow_failures:
    - go: master
install:
  - make vendor
  - make prepare_metalinter
script:
  - make build
  - make lint ERRORS_ONLY=true
