language: go
sudo: false
go:
  - tip
  - 1.x
  - 1.8
matrix:
  allow_failures:
    - go: tip
install:
  - make vendor
  - make prepare_metalinter
script:
  - make build
  - make lint ERRORS_ONLY=true
